# Generated by Django 5.0.4 on 2024-04-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_directions_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/icons/', verbose_name='Иконка'),
        ),
    ]
