# Generated by Django 5.0.4 on 2024-04-12 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_diagnostic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Записи', to='diagnostics.diagnostic', verbose_name='Диагностика')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Записи', to='diagnostics.doctor', verbose_name='Врач')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Записи', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись на диагностику',
                'verbose_name_plural': 'Записи на диагностику',
            },
        ),
    ]
