# Generated by Django 5.0.4 on 2024-04-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='directions',
        ),
    ]
