# Generated by Django 5.0.4 on 2024-04-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0006_remove_diagnostic_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка'),
        ),
    ]
