# Generated by Django 5.0.4 on 2024-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0007_alter_directions_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='timing',
            field=models.CharField(blank=True, null=True, verbose_name='Часы приёма'),
        ),
    ]
