# Generated by Django 5.0.4 on 2024-04-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_doctor_timing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
