# Generated by Django 5.0.4 on 2024-04-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='488685212216', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
