# Generated by Django 5.0.4 on 2024-04-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_ver_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='865543993175', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
